name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: pip install -r py/requirements.txt
      - name: Install R deps
        run: Rscript -e 'install.packages(c("reticulate","testthat","tidyverse","data.table","ggplot2"), repos="https://cloud.r-project.org")'
      - name: Run basic script
        run: Rscript scripts/01_preprocess.R
